sonata_media:
    db_driver: doctrine_orm
    default_context: default
    providers:
        image:
            resizer: sonata.media.resizer.square
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
            formats:
                small:  { width: 200 , quality: 80}
                medium: { width: 360 , quality: 80}
                big:    { width: 720 , quality: 80}
        sonata_collection:
            providers:
              - sonata.media.provider.image
            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}

        sonata_category:
            providers:
              - sonata.media.provider.image
            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}
    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     true