# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app_bundle.mail:
        class: AppBundle\Service\ContactService
        arguments: ["@swiftmailer.mailer"]

    admin.category:
        class: Application\Sonata\UserBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }

    admin.ingredient:
        class: Application\Sonata\UserBundle\Admin\IngredientAdmin
        arguments: [~, AppBundle\Entity\Ingredient, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Ingredient }

    admin.post:
        class: Application\Sonata\UserBundle\Admin\PostAdmin
        arguments: [~, AppBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Post }

    admin.recipe:
        class: Application\Sonata\UserBundle\Admin\RecipeAdmin
        arguments: [~, AppBundle\Entity\Recipe, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Recipe }

    admin.recipe_ingredient:
        class: Application\Sonata\UserBundle\Admin\RecipeIngredientAdmin
        arguments: [~, AppBundle\Entity\RecipeIngredient, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: RecipeIngredient }

    admin.step:
        class: Application\Sonata\UserBundle\Admin\StepAdmin
        arguments: [~, AppBundle\Entity\Step, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Step }

