services:
    app_bundle.post_content_listener:
        class: AppBundle\Listener\PostContentListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    app_bundle.recipe_nutrition_api_listener:
        class: AppBundle\Listener\RecipeNutritionApiListener
        arguments: ["@app_bundle.nutrition_api"]
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    app_bundle.nutrition_api:
        class: AppBundle\Service\NutritionApiService
        arguments: ["@guzzle.client.api_nutrition", "%nutrition_endpoint%"]

    app_bundle.content_optimizer:
        class: AppBundle\Service\ContentOptimizerService
        arguments: ["@sonata.media.provider.image", "@doctrine.orm.entity_manager"]

    app_bundle.contact:
        class: AppBundle\Service\ContactService
        arguments: ["@swiftmailer.mailer"]

    app_bundle.mail:
        class: AppBundle\Service\MailService
        arguments: ["@mailer", "@templating", "@doctrine.orm.entity_manager"]

    app_bundle.subscribe:
        class: AppBundle\Service\SubscribeService
        arguments: ["@doctrine.orm.entity_manager", "@app_bundle.mail"]

    admin.category:
        class: Application\Sonata\UserBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }

    admin.ingredient:
        class: Application\Sonata\UserBundle\Admin\IngredientAdmin
        arguments: [~, AppBundle\Entity\Ingredient, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Ingredient }

    admin.post:
        class: Application\Sonata\UserBundle\Admin\PostAdmin
        arguments: [~, AppBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Post }

    admin.recipe:
        class: Application\Sonata\UserBundle\Admin\RecipeAdmin
        arguments: [~, AppBundle\Entity\Recipe, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Recipe }

    admin.recipe_ingredient:
        class: Application\Sonata\UserBundle\Admin\RecipeIngredientAdmin
        arguments: [~, AppBundle\Entity\RecipeIngredient, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: RecipeIngredient }

    admin.step:
        class: Application\Sonata\UserBundle\Admin\StepAdmin
        arguments: [~, AppBundle\Entity\Step, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Step }

    admin.subscribe:
        class: Application\Sonata\UserBundle\Admin\SubscribeAdmin
        arguments: [~, AppBundle\Entity\Subscribe, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Subscribe }

    admin.url_show:
        class: Application\Sonata\UserBundle\Form\UrlType
        tags:
            - { name: form.type, alias: url_show }