# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    admin.category:
        class: Application\Sonata\UserBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
    admin.ingredient:
        class: Application\Sonata\UserBundle\Admin\IngredientAdmin
        arguments: [~, AppBundle\Entity\Ingredient, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Ingredient }
    admin.post:
        class: Application\Sonata\UserBundle\Admin\PostAdmin
        arguments: [~, AppBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Post }